from app.schemas.ai import *
from app.schemas.analytics import *
from app.schemas.audit_log import *
from app.schemas.auth import *
from app.schemas.common import *
from app.schemas.document import *
from app.schemas.employee import *
from app.schemas.equipment import *
from app.schemas.inventory import *
from app.schemas.lease import *
from app.schemas.maintenance import *
from app.schemas.message import *
from app.schemas.notification import *
from app.schemas.property import *
from app.schemas.report import *
from app.schemas.schedule import *
from app.schemas.settings import *
from app.schemas.tenant import *
from app.schemas.unit import *
from app.schemas.user import *
from app.schemas.vendor import *
from app.schemas.work_order import *
